### ISSUE TITLE
Important - Add background color to header

### ISSUE THREAD

**Issue by davecastlevania** [lewafa/lewafa.github.io#2]
https://github.com/lewafa/lewafa.github.io/blob/master/TeaCozy/resources/css/style.css#L24-L32

Add a black `background-color`

**Comment by lewafa** [comment]
body - has the background-color: black; 
why should the header still have background-color: black ?

**Comment by davecastlevania** [comment]
the header shows transparent when scrolling. since the header doesn't inherent from the body (element to element) you have to be specific to the header

**Comment by lewafa** [comment]
done. thanks.
