### ISSUE TITLE
Summary - Satisfactory

### ISSUE THREAD

**Issue by davecastlevania** [lewafa/lewafa.github.io#6]
Hey great job with this project so far. It shows that you are understanding how to use the flexbox model. I like how you were able to structure the HTML and CSS and still keep it clean. There were a few subtle changes that I would focus on that are outlined in the issues section. Mostly related to margins/background colors and how the header is transparent when you scroll. Those changes should fix that issue. Otherwise, keep up the good work!

**Comment by lewafa** [comment]
Thanks dave.
